version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: simple
    filename: logs/kedro.log
    maxBytes: 10485760
    backupCount: 3
    encoding: utf8
    delay: False

  rich:
    class: kedro.logging.RichHandler
    rich_tracebacks: True

loggers:
  kedro:
    level: WARNING

  pyspark_viz_spaceflights:
    level: INFO

root:
  level: WARNING
  handlers: [rich, info_file_handler]