version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO                  # << INFO para ver info en terminal si usas console
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO                  # << INFO para guardar info en disco
    formatter: simple
    filename: logs/kedro.log
    maxBytes: 10485760
    backupCount: 3
    encoding: utf8
    delay: False

  rich:
    class: kedro.logging.RichHandler
    rich_tracebacks: True
    level: INFO                  # << explícito

loggers:
  kedro:
    level: INFO
    propagate: False

  pyspark_viz_spaceflights:
    level: INFO
    propagate: False

root:
  level: INFO                    # << clave: el filtro global
  handlers: [rich, info_file_handler] 