version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: standard
    stream: ext://sys.stdout

loggers:
  org.apache.spark:
    level: ERROR
    handlers: [console]
    propagate: no

  org:
    level: ERROR
    handlers: [console]
    propagate: no

  py4j:
    level: ERROR
    handlers: [console]
    propagate: no

  pyspark:
    level: ERROR
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
