version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] %(name)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/kedro.log      # (Crea la carpeta logs/ antes de lanzar Kedro)
    maxBytes: 5_000_000           # Rota a ~5 MB por archivo
    backupCount: 3                # Conserva 3 copias anteriores
    encoding: utf8

root:
  level: INFO
  handlers: [console, file]

loggers:
  kedro:
    level: INFO
    handlers: [console, file]
    propagate: no
  warnings:             # <- Para integrar warnings Python (si usas captureWarnings)
    level: WARNING
    handlers: [console, file]
    propagate: no