run_id: "001" # Representa ejecucion global

cv_settings:
  n_splits: 5
  random_state: 42

model_parameters:
  LogisticAT:
    grid_001: # Representa combinacion de parametros
      dataset_name: train_ordinal
      param_grid:
        alpha: [0.1, 0.5]
        max_iter: [500]