run_id: "001" # Representa ejecucion global

training_datasets:
  - cleaned_46014_train_ordinal
  - cleaned_46025_train_ordinal
  - cleaned_46042_train_ordinal
  - cleaned_46053_train_ordinal
  - cleaned_46069_train_ordinal
  
test_datasets:
  - cleaned_46014_test_ordinal
  - cleaned_46025_test_ordinal
  - cleaned_46042_test_ordinal
  - cleaned_46053_test_ordinal
  - cleaned_46069_test_ordinal

cv_settings:
  n_splits: 5
  random_state: 42

model_parameters:
  LogisticAT:
    grid_001: # Representa combinacion de parametros
      param_grid:
        alpha: [0.5, 0.9]
        max_iter: [500, 1000]